postgres:
  host: dbads.makakolabs.ca
  port: 5432
  dbname: ***REMOVED***
  user: postgres
  password: test123
  sslmode: disable
dbinfo:
  table: ***REMOVED***
  schema: public
  monitor: go_postgres_monitor
elastic:
  host: elastic.makakolabs.ca
  port: 9200
  


