postgres:
  host: 192.168.2.200
  port: ***REMOVED***
  dbname: ***REMOVED***
  user: ***REMOVED***
  password: ***REMOVED***
  sslmode: disable
dbinfo:
  table: ***REMOVED***
  schema: public
  monitor: go_postgres_monitor
elastic:
  host: 192.168.2.200
  port: 9200
  
